spring:
  datasource:
    url: jdbc:mysql://localhost:3307/onion-db
    username: onion-user
    password: onion1!
    driverClassName: com.mysql.cj.jdbc.Driver

  #JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  # Hibernate 설정
    show-sql: true
    properties:
      hibernate:
        format_sql: true