spring:
  datasource:
    url: jdbc:mysql://localhost:3307/onion-db
    username: onion-user
    password: onion1!
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379

  #JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  # Hibernate 설정
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.authentication: DEBUG

jwt:
  cookieName: onion_token
  secret: 4de254442b400013b9fe0fd3314f7e43b7e4a9bc0d99837ad8e057ebf31f0b86
  expire: 86400000 # 24 hours (in milliseconds);

client_domain: http://localhost:3000